name: ci
on: [push]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Build
        run: npm ci
      - name: Test
        run: npm test
      - name: Build API Doc
        run: npm run apidoc
      - name: Deploy API Doc
        uses: kayahr/deploy-github-pages-action@v1
        with:
          node-version: "doc"
